import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      className="min-h-[100vh] max-h-[100vh] h-[100vh] m-0 p-0"
      
    >
      
      <body
        id="root"
        className={`${geistSans.variable} ${geistMono.variable} antialiased  min-h-[100%] max-h-[100%] h-[100%] m-0 grid grid-rows-[10%_80%_10%] `}
        style={{background:"linear-gradient(to right, #707fadff, #6076baff, #5069b6ff)"}}
      >
        <div className="grid grid-cols-[33.3%_33.3%_33.3%] items-center justify-center">
            <div className="grid items-center col-span-2 justify-center h-full bg bg-gray-500">
              <h1 className="text-2xl ms-142 font-bold text-white drop-shadow-lg">Cristofer Avilés Vega</h1>
            </div>
            <div className="grid grid-cols-[25%_25%_25%_25%] items-center justify-center h-full max-h-[100%] min-h-[100%] bg bg-gray-500">
              <Link
                href="/"
                className="grid grid-cols-[35%_65%] h-full justify-center items-center max-h-[100%] min-h-[100%]"
              >
                <div
                  className="w-full h-full max-h-[100%] min-h-[100%] grid justify-center items-center"
                >
                  <img 
                    src="iconos/perfil.png"
                    className="max-h-[50%] min-h-[50%] h-[50%] m-0 p-0 hover:scale-120 transform transition duration-300 ease-in-out"
                    style={{border: "2px solid white", borderRadius: "50%"}}
                  ></img>
                </div>
                <div
                  className="grid items-center h-full font-bold text-white drop-shadow-lg"
                >
                  Perfil
                </div>
              </Link>

              <Link
                href="/contacto"
                className="grid grid-cols-[35%_65%] h-full justify-center items-center max-h-[100%] min-h-[100%]"
              >
                <div
                  className="w-full h-full max-h-[100%] min-h-[100%] grid justify-center items-center"
                >
                  <img 
                    src="iconos/contacto.png"
                    className="max-h-[50%] min-h-[50%] h-[50%] m-0 p-0 hover:scale-120 transform transition duration-300 ease-in-out"
                    style={{border: "2px solid white", borderRadius: "50%"}}
                  >

                  </img>
                </div>
                <div
                  className="grid items-center h-full font-bold text-white drop-shadow-lg"
                >
                  Contacto
                </div>
              </Link>
              {/* <Link
                href="/muestras"
                className="grid grid-cols-[35%_65%] h-full justify-center items-center max-h-[100%] min-h-[100%]"
              >
                <div
                  className="w-full h-full max-h-[100%] min-h-[100%] grid justify-center items-center"
                >
                  <img 
                    src="iconos/codigo.png"
                    className="max-h-[50%] min-h-[50%] h-[50%] m-0 p-0"
                  ></img>
                </div>
                <div
                  className="h-full grid items-center"
                >
                  Muestras
                </div>
              </Link> */}
            </div>
          </div>

          <div 
            style={{background: "linear-gradient(to right, #e8e8e8ff, #e6e5e5ff)"}}
            className="grid items-center min-h-[85%] max-h-[85%] h-[85%] min-w-[82.5%] max-w-[82.5%] w-[82.5%] m-auto border rounded-3xl bg bg-gray-300">
            
              {children}
                       
          </div>

          <footer className="grid grid-cols-[10%_10%_10%] justify-center h-full p-0 m-0">
            <a
              className="flex items-center gap-2 hover:underline hover:underline-offset-4 justify-center text-white font-bold"
              href="https://www.linkedin.com/in/cristofer-avil%C3%A9s-638716203/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                aria-hidden
                src="/linkedin.png"
                alt="File icon"
                width={48}
                height={48}
              />
              LinkedIn
            </a>
            
            <a
              className="flex items-center gap-2 hover:underline hover:underline-offset-4 justify-center text-white font-bold"
              href="https://github.com/cavilesv/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                aria-hidden
                src="/globe.svg"
                alt="Globe icon"
                width={28}
                height={28}
              />
              GitHub
            </a>
          </footer>
      </body>
      
    </html>
  );
}
